name: Kernel CI

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'device codename (RMX3171)'
          required: true
      repo:
          description: 'Kernel source link'
          required: true
      branch:
          description: 'Kernel source branch'
          required: true   

env:
  TZ: Asia/Kolkata
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: ${{ secrets.TOKEN }}
  chat_id: ${{ secrets.CHAT_ID }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "kushagrasinghbisen"
          git config --global user.email "kushagrasinghbisen@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex glibc-source g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch
          neofetch

      - name: Lets compile
        run: |
          git clone $REPO -b $BRANCH kernel 
          cd kernel
            wget https://gist.githubusercontent.com/kushagrasinghbisen/008e7bbc2b94b6c121a33175b33bcd63/raw/14c34e004ce4d8216642fa9570446a782072aa7e/buildscript.sh
            bash buildscript.sh
